on:
  push:
      branches:
        - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntsu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - uses: actions/checkout@v3
    - run: go test ./... -coverprofile=converge.out
    - name: report coverage
      uses: klloW/octocov-action@v0
