on:
  push:
      branches:
        - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntsu-latest
    services:
      mysql:
        image: mysql:8
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: todo
          MYSQL_USER: todo
          MYSQL_PASSWORD: todo
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - uses: actions/checkout@v3
    - run: go test ./... -coverprofile=converge.out
    - name: report coverage
      uses: klloW/octocov-action@v0
